spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # connection pool name
      pool-name: DateHikariCP
      # minimum-idle connection
      minimum-idle: 5
      # idle connection maximum time, default is 600000(10 minutes)
      idle-timeout: 1800000
      # maximum connection number, default is 10
      maximum-pool-size: 10
      # automatically commit the connection returned from connection pool
      auto-commit: true
      # 0 represents eternal, default is 1800000(30 minutes)
      max-lifetime: 1800000
      # connection-timeout, default 30000(30 seconds)
      connection-timeout: 3000
      # testing whether connection can use query
      connection-test-query: SELECT 1
  # redis setting
  redis:
    # server address
    host: 127.0.0.1
    # port
    port: 6379
    # database
    database: 0
    # timeout
    timeout: 10000ms
    lettuce:
      pool:
        # default 8
        max-active: 8
        # default -1
        max-wait: 1000ms
        # default 8
        max-idle: 200
        # default 0
        min-idle: 5
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.seckill.pojo

logging:
  level:
    com.example.seckill.mapper: debug
